# Classify Iris data species using Logistic Regression project


In [1]:
import numpy as np
import pandas as pd


In [16]:
df = pd.read_csv("C:/Users/DELL/Desktop/Career/Projects/Iris/iris.data.csv" , header=None)


In [17]:
df.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [18]:
df.columns=['sepallength','sepalwidth','petallength','petalwidth','class']
df.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [19]:
df.dtypes

sepallength    float64
sepalwidth     float64
petallength    float64
petalwidth     float64
class           object
dtype: object

In [22]:
df.describe()

sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [23]:
#check if there's null data
df.isnull().sum()

sepallength    0
sepalwidth     0
petallength    0
petalwidth     0
class          0
dtype: int64

In [28]:
from sklearn.preprocessing import LabelEncoder

In [35]:
#convert categorical target into discrete continous
encode = LabelEncoder()
df['class'] = encode.fit_transform(df['class'])
df.head()

sepallength  sepalwidth  petallength  petalwidth  class
0          5.1         3.5          1.4         0.2      0
1          4.9         3.0          1.4         0.2      0
2          4.7         3.2          1.3         0.2      0
3          4.6         3.1          1.5         0.2      0
4          5.0         3.6          1.4         0.2      0

In [36]:
from sklearn.model_selection import train_test_split

In [39]:
#divide data intro train and test
train , test = train_test_split(df , test_size=0.2 , random_state=0)
print(train.shape)
print(test.shape)

(120, 5)
(30, 5)


In [49]:
#divide data into features and target
train_X = train.drop(['class'] , axis=1)
train_y = train[['class']]

In [50]:
train_X.head()

sepallength  sepalwidth  petallength  petalwidth
137          6.4         3.1          5.5         1.8
84           5.4         3.0          4.5         1.5
27           5.2         3.5          1.5         0.2
127          6.1         3.0          4.9         1.8
132          6.4         2.8          5.6         2.2

In [51]:
train_y.head()

class
137      2
84       1
27       0
127      2
132      2

In [52]:
test_X = test.drop(['class'] , axis=1)
test_y = test[['class']]

In [57]:
print(test_X.shape)
print(test_y.shape)


(30, 4)
(30, 1)


In [91]:
#Normalize features
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_X).transform(train_X)
ss.fit(test_X).transform(test_X)

array([[ 0.14956537, -0.58304897,  0.94512598,  1.91948971],
       [ 0.43000045, -1.9460206 ,  0.2829358 , -0.10102577],
       [-0.27108724,  2.59721815, -1.28224097, -1.25560605],
       [ 2.25282843, -0.35588703,  1.66751526,  1.0535545 ],
       [-0.97217492,  0.77992265, -1.22204187, -1.25560605],
       [ 0.85065306,  0.55276071,  1.48691794,  2.06381224],
       [-0.97217492,  1.00708459, -1.34244008, -1.11128352],
       [ 1.41152321,  0.09843684,  0.70432955,  0.6205869 ],
       [ 1.55174074, -0.58304897,  0.76452866,  0.47626436],
       [ 0.57021798, -0.58304897,  0.2829358 ,  0.33194183],
       [ 0.57021798, -1.03737285,  1.24612151,  0.47626436],
       [ 0.9908706 ,  0.32559878,  0.58393134,  0.6205869 ],
       [ 0.57021798, -0.58304897,  0.70432955,  0.18761929],
       [ 1.13108813, -0.58304897,  0.64413044,  0.6205869 ],
       [ 0.57021798, -0.35588703,  0.70432955,  0.47626436],
       [-1.11239246,  0.09843684, -1.22204187, -1.39992858],
       [ 0.43000045, -0.

In [104]:
from sklearn.linear_model import LogisticRegression

In [121]:
lr = LogisticRegression(solver='liblinear')
lr.fit(train_X , train_y)
lr

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [127]:
pred_values_prob = lr.predict_proba(test_X)
pred_values_prob[0:5]

array([[8.48551777e-04, 1.75187088e-01, 8.23964360e-01],
       [2.55349832e-02, 8.28280027e-01, 1.46184990e-01],
       [9.38770402e-01, 6.12219632e-02, 7.63524745e-06],
       [1.95595855e-04, 3.92858391e-01, 6.06946013e-01],
       [8.59320284e-01, 1.40622105e-01, 5.76113536e-05]])

In [122]:
pred_values = lr.predict(test_X)
pred_values

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 2,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

##Evaluation

In [112]:
from sklearn.metrics import f1_score

In [123]:
score = f1_score(test_y , pred_values , average='weighted')
score

0.9672820512820512

In [124]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_y , pred_values))

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


In [129]:
from sklearn.metrics import log_loss
print(log_loss(test_y , pred_values_prob))

0.32646323054581117


In [126]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y , pred_values)

0.9666666666666667